### ISSUE TITLE
 I receive the warning below.

### ISSUE THREAD

**Issue by sebahattinkoc** [shakeelosmani/MvcAffableBean#1] opened 2017-05-31 07:37 UTC
Foreign key 'FK_dbo.OrderedProducts_dbo.Products_ProductId' references invalid table 'dbo.Products'.
Could not create constraint. See previous errors.

Line 94:         public int GetCount()
Line 95:         {
Line 96:             int? count =
Line 97:                 (from cartItems in db.Carts where cartItems.CartId == ShoppingCartId select (int?) cartItems.Count).Sum();
Line 98: 

What can I do. ?

Is there a new version?

**Comment by sebahattinkoc** [comment] 2017-05-31 10:32
Delete the migrations folder in your project.

It was dissolved

**Comment by amirzf** [comment] 2017-06-07 10:28
hi
1- when click category    give me error:HTTP Error 404.0 - Not Found

2- project will run but when registered  

give me error:
**A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified)

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

SQLExpress database file auto-creation error: 

**The connection string specifies a local Sql Server Express instance using a database location within the application's App_Data directory. The provider attempted to automatically create the application services database because the provider determined that the database does not exist. The following configuration requirements are necessary to successfully check for existence of the application services database and automatically create the application services database:**

If the application is running on either Windows 7 or Windows Server 2008R2, special configuration steps are necessary to enable automatic creation of the provider database. Additional information is available at: http://go.microsoft.com/fwlink/?LinkId=160102. If the application's App_Data directory does not already exist, the web server account must have read and write access to the application's directory. This is necessary because the web server account will automatically create the App_Data directory if it does not already exist.
If the application's App_Data directory already exists, the web server account only requires read and write access to the application's App_Data directory. This is necessary because the web server account will attempt to verify that the Sql Server Express database already exists within the application's App_Data directory. Revoking read access on the App_Data directory from the web server account will prevent the provider from correctly determining if the Sql Server Express database already exists. This will cause an error when the provider attempts to create a duplicate of an already existing database. Write access is required because the web server account's credentials are used when creating the new database.
Sql Server Express must be installed on the machine.
The process identity for the web server account must have a local user profile. See the readme document for details on how to create a local user profile for both machine and domain accounts.****

thanks  shakeelosmani

**Closed as completed** 2018-02-16 17:09 UTC
